version: '3'
services:
  docker-master:
    build: ./docker-master
    image: docker-master
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/minio/export/users:/var/data/users/
    environment:
      - "TOKEN=ZYX321"

  # proxy:
  #   build: ./proxy
  #   image: proxy
  #   network_mode: "service:[proxy]"
  # server:
  #   build: ./server
  #   image: server
  #   network_mode: "service:[proxy]"
  # client:
  #   build: ./client
  #   image: client
  #   network_mode: "service:[proxy]"

  # minio:
  #   image: minio/minio
  #   hostname: data
  #   environment:
  #     - "MINIO_ACCESS_KEY=2HjzPsSAS9JamoPbKg2e"
  #     - "MINIO_SECRET_KEY=nZkqIbhtvorQVlzGtslQnVmqulSwpulNMxZsGEBh"
  #   ports:
  #     - "9000:9000"
  #   volumes:
  #     - /var/minio/export:/var/minio/export
  #     - /var/minio/config:/root/.minio
  #   command: server /var/minio/export

  kafka:
    image: spotify/kafka
    ports:
      - "9092:9092"
      # and zookeeper
      - "2181:2181"
    environment:
      - "ADVERTISED_PORT=9092"

  kafka-websocket:
      build: ./kafka-websocket
      image: kafka-websocket
      ports:
        - "7080:7080"

# networks:
#   internal:
#     driver: bridge
#     ipam:
#       driver: default
#       config:
#         - subnet: 10.5.0.0/16
