version: '3'
services:
  client:
    build: ./client
    image: var-tool/client:latest
    ports:
      - "80:80"

  server:
    build: ./server
    image: var-tool/server:latest
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./data:/usr/src/app/data"
    command: lein run
