version: '3'
services:
  # server:
  #   build: ./server
  #   image: var-tool/server:latest
  #   network_mode: "host"
  #   networks:
  #     - external

  client:
    build: ./client
    image: var-tool/client:latest
    network_mode: "host"
    networks:
      - external

  # docker-master:
  #   build: ./docker-master
  #   image: var-tool/docker-master:latest
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - /var/minio/export/users:/var/data/users/
  #   environment:
  #     - "TOKEN=ZYX321"
  #   networks:
  #     - internal

  kafka:
    image: spotify/kafka:latest
    ports:
      - "9092:9092"
      # and zookeeper
      - "2181:2181"
    environment:
      - "ADVERTISED_PORT=9092"
    networks:
      - internal
      - external

  kafka-websocket:
      build: ./kafka-websocket
      image: var-tool/kafka-websocket:latest
      ports:
        - "7080:7080"
      network_mode: "host"
      networks: 
        - external

networks:
  internal:
    driver: bridge
    internal: true
  external:
    driver: bridge
